apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
  labels:
    app: k8-flask-webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: k8-flask-webapp
