apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: k8-flask-webapp
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32765
  selector:
    app: k8-flask-webapp
